### ISSUE TITLE
Adding a schema via SEO panel and via a custom extractor does not output JSON

### ISSUE THREAD

**Issue by alexej-d** [dachcom-digital/pimcore-seo#27]
| Q                | A
| ---------------- | -----
| Bug report?      | yes?
| Feature request? | no
| BC Break report? | no
| RFC?             | no

It seems adding schema is not possible with this bundle as it looks like a new HeadMeta instance is being spin up and it's rawItems are not being output when calling the pimcore_head_meta function.

I have tested this on Pimcore 6.9 and bundle version 1.0, and Pimcore 10.2.5 and the newest bundle version.

**Comment by dennistiboni-extera** [comment]
I ran into the same problem. There is a solution @solverat ?

**Comment by solverat** [comment]
I'm afraid but I don't get the issue here.

Adding a schema block to my document / object:

```ld+json
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "WebSite",
    "url": "http://website.com",
    "name": "wbs",
    "description": "Web Studio"
}
</script>
```
### Object
![image](https://user-images.githubusercontent.com/700119/201736170-17beed6f-e327-4c1f-a73e-eb4e3f4d2f6d.png)
### Document
![image](https://user-images.githubusercontent.com/700119/201736342-4b7d10a7-50e1-4e48-b1ea-33b3928f9f9e.png)

Within my main layout template:
![image](https://user-images.githubusercontent.com/700119/201736257-f7aa0e62-a9b9-4f3b-8dc5-d7ef8363d76c.png)

And my object layout:
![image](https://user-images.githubusercontent.com/700119/201736464-97dbb8f7-4f6b-4166-83c4-4a3082946abb.png)

...everything works fine:

![image](https://user-images.githubusercontent.com/700119/201736641-00fbc008-55c6-41db-a9a1-a91bf286c412.png)

**Comment by solverat** [comment]
Please check if you've completed the setup liked described here: https://github.com/dachcom-digital/pimcore-seo/blob/master/docs/00_Setup.md#setup

**Comment by alexej-d** [comment]
@solverat I came across this bug with version 2.0.1 of your bundle. At version 2.2 there seems to not be any issues regarding LD+JSON
