### ISSUE TITLE
Pimcore 11 Support

### ISSUE THREAD

**Issue by bitfactory-edo-freriks** [dachcom-digital/pimcore-seo#49]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Hey there, thanks for your bundle, we've implemented it succesfully but are now looking to upgrade our pimcore instance to version 11, are you working on an update for pimcore 11? And is there an ETA for this update? 

Thanks in advance, I hope this is the right place to ask this question.

**Comment by solverat** [comment]
Hey there. V3 with Pimcore 11 support will be available in the next two or three weeks!

**Comment by dlhck** [comment]
@solverat any update on that? :) Tell me if you need help/support

**Comment by dlhck** [comment]
@solverat I added a PR (#52) with the fixes that are needed - I tested it on one installation. Please also do your testing. I added the `ramsey/uuid-doctrine` so that the `QueueEntry` can still use UUIDs as this feature is deprecated with newer doctrine versions.

**Comment by solverat** [comment]
@davidhoeck Thanks for your contribution. We're doing our best to keep our bundles on track with the latest pimcore releases. Major updates are rare moments, where we can introduce BC breaks if required but also make some strategic changes / improvements.

I know, the response times are a bit slow when it comes to major updates, but keeping 30 OS projects in line - that is something :)

So please, before investing valuable time: Wait for our feedback, before creating PRs to this extent! 

Having said that, I'm afraid, but we can't merge your PR, since we've already started with the implementation (we're also moving to the new bundle structure for example) so merging your PR would be more work than help.

I hope you understand our decision.

BTW: As mentioned, the PR for P11 is almost done and will be available this week.

**Comment by dlhck** [comment]
@solverat no problem! :) I had to do it anyway so that the team can continue working on a project. If you can provide the new release this week even better! 🚀

**Comment by solverat** [comment]
Done. https://github.com/dachcom-digital/pimcore-seo/releases/tag/v3.0.0
