### ISSUE TITLE
Questions and suggestions SEO Bundle

### ISSUE THREAD

**Issue by BentBr** [dachcom-digital/pimcore-seo#60]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

Hey Folks!
It's me Bent, from [Blackbit](https://www.blackbit.com/en), the creators of the [Blackbit Data Director](https://pimcore.com/en/developers/marketplace/blackbit_digital_commerce/pimcore-data-director_e103850) (I guess we know each other 🙃 )

I do have a couple of questions and change / feature requests as follows:

- The SEO Bundle has custom fields for meta description and title. Why not using the one pimcore documents already provide?
Is there a function to use Pimcore's fields out-of-the-box?
- SEO Bundle does not support (yet) [JSON-LD](https://json-ld.org/) after [schema.org](schema.org). Are you already thinking of implementing it?
- Regarding install of your plugin, you have a query to create custom database entries:
https://github.com/dachcom-digital/pimcore-seo/blob/master/config/install/sql/install.sql
-> this lead to an issue on our side during migration of versions of a project (due to not separately install of the plugin). We expected to have a Migration set and available which was not present.
What's the reason of not using a Magration?

**Comment by solverat** [comment]
Hi @BentBr!

- If you're using the SEO Bundle, the default SEO block for documents will be removed. We're not using the default one, because we want to consolidate the UI => Everything is in the same tab (regardless if you're adding data for documents or objects). But it's also for DX: Fetching/modifying metadata always works the same (see documentation)
- Actually, it does? Not sure what you mean. If you're talking about a fully implemented schema preset definition, you're right, that is not available because it would be a huge feature and we currently don't see any benefits to invest in. 
  - ![image](https://github.com/dachcom-digital/pimcore-seo/assets/700119/27519f08-9c83-43fa-92a9-658eff8bbf9e)
- The SEO bundle has an Installer class, which is pimcore standard. Of course, this could be a migration too (which would be my preferred way too today, but this (and other) bundle has been introduced that way some years ago and we never ran into any issues by using an installer

**Comment by BentBr** [comment]
Thank you for your response!
We indeed did not use the latest version - my bad.
