### ISSUE TITLE
og:image should how full URL (with http://domain.com)

### ISSUE THREAD

**Issue by james-cfag** [dachcom-digital/pimcore-seo#9]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

og:image should how full URL (with http://domain.com).

Any comment? I use the Facebook Open Graph with image tagged, but the generated code shows only the path, which Facebook would not load.

Thanks!

James

**Comment by solverat** [comment]
@james-cfag Thanks for your investigation! You're right, image urls have to be absolute.

I needed to close your PR in favor of bdd4078d4d33dc49069b4961c88a7cbb170cab72. Previous, I decided to store relative image paths in database to keep the performance up! But I think that's not a good idea (+ storing absolute URLs in db wouldn't be possible because of multisites) - so I've changed that (We now fetch asset paths + URL in realtime!

Thanks again!
